[versions]
kotlin = "2.1.21"
ksp = "2.1.21-2.0.2"
android = "8.10.1"
compose = "1.8.3"
rikka = "4.4.0"
room = "2.7.2"
paging = "3.3.6"
ktor = "3.1.3"
destinations = "2.2.0"
coil = "3.2.0"
shizuku = "13.1.5"

[libraries]
kotlin_stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin_test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx_serialization_json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.1"
ktor_server_core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor_server_cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor_server_content_negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor_client_core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor_client_okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor_client_content_negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor_serialization_kotlinx_json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
compose_ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose_ui_graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose" }
compose_animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose_animation_graphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "compose" }
compose_preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose_tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose_junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose_icons = "androidx.compose.material:material-icons-extended:1.7.8"
compose_material3 = "androidx.compose.material3:material3:1.3.2"
compose_activity = "androidx.activity:activity-compose:1.10.1"
compose_navigation = "androidx.navigation:navigation-compose:2.9.0"
androidx_appcompat = "androidx.appcompat:appcompat:1.7.1"
androidx_core_ktx = "androidx.core:core-ktx:1.16.0"
androidx_lifecycle_runtime_ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.9.1"
androidx_junit = "androidx.test.ext:junit:1.2.1"
androidx_annotation = "androidx.annotation:annotation:1.9.1"
androidx_espresso = "androidx.test.espresso:espresso-core:3.6.1"
androidx_room_runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx_room_compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx_room_ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx_room_paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx_splashscreen = "androidx.core:core-splashscreen:1.0.1"
androidx_paging_runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
androidx_paging_compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
google_accompanist_drawablepainter = "com.google.accompanist:accompanist-drawablepainter:0.37.3"
junit = "junit:junit:4.13.2"
tencent_mmkv = "com.tencent:mmkv:2.2.2"
rikka_processor = { module = "dev.rikka.tools.refine:annotation-processor", version.ref = "rikka" }
rikka_annotation = { module = "dev.rikka.tools.refine:annotation", version.ref = "rikka" }
rikka_shizuku_api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku" }
rikka_shizuku_provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku" }
lsposed_hiddenapibypass = "org.lsposed.hiddenapibypass:hiddenapibypass:6.1"
destinations_core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "destinations" }
destinations_ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "destinations" }
coil_compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil_network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
coil_gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }
reorderable = "sh.calvin.reorderable:reorderable:2.5.1"
exp4j = "net.objecthunter:exp4j:0.4.8"
toaster = "com.github.getActivity:Toaster:13.0"
permissions = "com.github.getActivity:XXPermissions:23.0"
json5 = "li.songe:json5:0.3.4"
utilcodex = "com.blankj:utilcodex:1.31.1"
activityResultLauncher = "com.github.DylanCaiCoding:ActivityResultLauncher:1.1.2"
floatingBubbleView = "io.github.torrydo:floating-bubble-view:0.6.5"
kevinnzouWebview = "io.github.kevinnzou:compose-webview:0.33.6"

[plugins]
kotlin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin_multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin_parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin_compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android_library = { id = "com.android.library", version.ref = "android" }
android_application = { id = "com.android.application", version.ref = "android" }
androidx_room = { id = "androidx.room", version.ref = "room" }
google_ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
rikka_refine = { id = "dev.rikka.tools.refine", version.ref = "rikka" }
benmanes_version = "com.github.ben-manes.versions:0.52.0"
littlerobots_version = "nl.littlerobots.version-catalog-update:1.0.0"
