[versions]
kotlin = "2.3.0"
serialization = "1.10.0"
ksp = "2.3.5"
agp = "9.0.0"
compose = "1.10.2"
nav3 = "1.0.0"
room = "2.8.4"
paging = "3.4.0"
ktor = "3.4.0"
atomicfu = "0.31.0"
coil = "3.3.0"
refine = "4.4.0"
shizuku = "13.1.5"
loc = "0.5.4"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "compose" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-icons = "androidx.compose.material:material-icons-extended:1.7.8"
compose-material3 = "androidx.compose.material3:material3:1.4.0"
compose-activity = "androidx.activity:activity-compose:1.12.3"
androidx-appcompat = "androidx.appcompat:appcompat:1.7.1"
androidx-core-ktx = "androidx.core:core-ktx:1.17.0"
androidx-lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.10.0"
androidx-lifecycle-service = "androidx.lifecycle:lifecycle-service:2.10.0"
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3" }
androidx-material3-adaptive-navigation3 = "androidx.compose.material3.adaptive:adaptive-navigation3:1.3.0-alpha07"
androidx-lifecycle-viewmodel-navigation3 = "androidx.lifecycle:lifecycle-viewmodel-navigation3:2.10.0"
androidx-junit = "androidx.test.ext:junit:1.3.0"
androidx-annotation = "androidx.annotation:annotation:1.9.1"
androidx-espresso = "androidx.test.espresso:espresso-core:3.7.0"
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-splashscreen = "androidx.core:core-splashscreen:1.2.0"
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
google-accompanist-drawablepainter = "com.google.accompanist:accompanist-drawablepainter:0.37.3"
junit = "junit:junit:4.13.2"
rikka-refine-processor = { module = "dev.rikka.tools.refine:annotation-processor", version.ref = "refine" }
rikka-refine-annotation = { module = "dev.rikka.tools.refine:annotation", version.ref = "refine" }
rikka-shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku" }
rikka-shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku" }
lsposed-hiddenapibypass = "org.lsposed.hiddenapibypass:hiddenapibypass:6.1"
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }
loc-annotation = { module = "li.songe.loc:loc-annotation", version.ref = "loc" }
reorderable = "sh.calvin.reorderable:reorderable:3.0.0"
exp4j = "net.objecthunter:exp4j:0.4.8"
toaster = "com.github.getActivity:Toaster:13.8"
permissions = "com.github.getActivity:XXPermissions:28.0"
device = "com.github.getActivity:DeviceCompat:2.5"
json5 = "li.songe:json5:0.5.0"
activityResultLauncher = "com.github.DylanCaiCoding:ActivityResultLauncher:1.1.2"
kevinnzouWebview = "io.github.kevinnzou:compose-webview:0.33.6"

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
androidx-room = { id = "androidx.room", version.ref = "room" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
rikka-refine = { id = "dev.rikka.tools.refine", version.ref = "refine" }
loc = { id = "li.songe.loc", version.ref = "loc" }
benmanes-version = "com.github.ben-manes.versions:0.53.0"
littlerobots-version = "nl.littlerobots.version-catalog-update:1.0.1"
