name: Build-Apk

on:
  workflow_dispatch:

  push:
    branches:
      - '**'
    paths-ignore:
      - 'LICENSE'
      - '*.md'
      - '.github/**'

jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, 'chore:') && !startsWith(github.event.head_commit.message, 'chore(') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}

      - name: write gkd secrets info
        run: |
          echo ${{ secrets.GKD_STORE_FILE_BASE64 }} | base64 --decode > ${{ github.workspace }}/gkd.jks
          echo GKD_STORE_FILE='${{ github.workspace }}/gkd.jks' >> gradle.properties
          echo GKD_STORE_PASSWORD='${{ secrets.GKD_STORE_PASSWORD }}' >> gradle.properties
          echo GKD_KEY_ALIAS='${{ secrets.GKD_KEY_ALIAS }}' >> gradle.properties
          echo GKD_KEY_PASSWORD='${{ secrets.GKD_KEY_PASSWORD }}' >> gradle.properties

      - run: chmod 777 ./gradlew
      - run: ./gradlew app:assembleGkdRelease

      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: app/build/outputs/apk/gkd/release

      - uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: app/build/outputs
